cms2-3572 Альфа версия
Umisoft/gui-installation-script pull request #1
Opened 2020-11-30 11:39 UTC by SeeleBlack

Initial commit.
Альфа версия.

2020-11-30 14:02 UTC, madGrant requested changes

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +<?php
https://github.com/Umisoft/umi.cms.2/blob/master/CODINGSTANDARDS.md#%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF-%D0%B2-php

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +class installCest
https://github.com/Umisoft/umi.cms.2/blob/master/CODINGSTANDARDS.md#%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +    public const TIMEOUT = 420;
https://github.com/Umisoft/umi.cms.2/blob/master/CODINGSTANDARDS.md#%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D1%8B-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +    /*Основной метод. */
не описаны принимаемые значения

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +{
фигурная скобка в объявлении класса должна быть на том же уровне

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +    {
фигурная скобка в объявлении метода должна быть на том же уровне

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +    public function install(AcceptanceTester $I)
$I - крайне плохой нейминг для аргумента, имя должно отражать суть

2020-11-30 14:02 UTC, madGrant commented on tests/acceptance/installCest.php
> +        //Первичный парсинг всех данных
Комментарии внутри методов делать не нужно, группы методов, которые необходимо продокументировать, лучше вынести в отдельный метод с phpDoc

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Отвечает за ввод данных админа*/
phpDoc и имя метода должны отражаться его действие.

Этот метод заполняется форму данных администратора

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
пробелы до и после =

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    public function svUserInstaller(){
пробел перед {

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    public function templateInstaller($type){
phpDoc и имя метода должны отражаться его действие.

Этот метод выбирает устанавливаемый демошаблон

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +            case "demo":
всё, что внутри case лучше помещать в фигурные скобки для читабельности

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                if ($templateName!="_blank") echo("\nНе найден шаблон с именем $templateName.\nПроверьте название в файле install.ini. Если название корректное, то убедитесь, что этот шаблон привязан
все, что после условия в if надо помещать в фигурные скобки и переносить на следующую строку

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                $this->searchTemplateInstaller(2);
что такое 2? Магические числа - это плохо

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                $this->searchTemplateInstaller(1);
что такое 1? Магические числа - это плохо

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
пробел до и после =

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    /* Установка через поиск.
phpDoc - Установка через поиск
имя метода - searchTemplateInstaller
вопрос - что реально метод делает?

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +     * Используется для 1 и 2 типа решения
1 и 2, что это?

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
$I -плохой нейминг и пробелы до и после =

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Вводит все поля и устанавливает всё до шаблона*/
Лучше написать, какие формы заполняет метод

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Формирует xpath адрес для полученного типа решения
Если метод возвращает xpath. то лучше его и назвать getFooBarXpath

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    * @param $number
нужно описание аргумента

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    {
фигурная скобка должна быть в строке объявления метода

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    public function __construct(\AcceptanceTester $I, $installIni)
$I - плохой нейминг

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    protected $I;
$I - плохой нейминг

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +class installPages
Классу и всем свойства нужно писать phpDoc

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +namespace Page\Acceptance;
https://github.com/Umisoft/umi.cms.2/blob/master/CODINGSTANDARDS.md#%D0%BE%D1%82%D1%81%D1%82%D1%83%D0%BF-%D0%B2-php

2020-11-30 14:02 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +    public static $searchResultOfSite = "//div[@class=\"site\"]";
Почему методы публичные и статичные?

2020-12-06 17:28 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +<?php
исправил

2020-12-06 17:29 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +class installCest
исправил

2020-12-06 17:39 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    public const TIMEOUT = 420;
исправил

2020-12-06 17:51 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    /*Основной метод. */
исправил

2020-12-06 17:56 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +{
исправил

2020-12-06 17:57 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    {
исправил

2020-12-06 18:16 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    public function install(AcceptanceTester $I)
исправил, надеюсь передал)

2020-12-06 19:05 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +        //Первичный парсинг всех данных
убрал комментарии, не вижу смысла в новых методах т.к. мне кажется, что это усложнит код

2020-12-06 19:06 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Отвечает за ввод данных админа*/
исправил

2020-12-06 19:06 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
исправил

2020-12-06 19:06 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    public function svUserInstaller(){
исправил

2020-12-06 19:08 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    public function templateInstaller($type){
исправил

2020-12-06 19:11 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +            case "demo":
исправил

2020-12-06 19:11 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                if ($templateName!="_blank") echo("\nНе найден шаблон с именем $templateName.\nПроверьте название в файле install.ini. Если название корректное, то убедитесь, что этот шаблон привязан
исправил

2020-12-06 21:22 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                $this->searchTemplateInstaller(2);
Есть xpath "//label[@for=\"type_of_site$number\"]/span"; куда вместо $number подставляется это "магическое" число. Всё дело в том, что этот xpath динамический в отличии от других статических xpath на страничке.
Скрин этой странички ниже
![image](https://user-images.githubusercontent.com/34538812/101292575-2f6b1800-3832-11eb-9797-dbecf313435e.png)

т.е. switch-case конструкция отвечает за отправку номера решения внутри системы вместе с логикой.

Если это не очень хорошо - подскажи, как сделать лучше.
Я могу "захардкодить" 4 переменные с разными xpath, но такое решение мне показалось лучше.
Словарик мне показался нерациональным.

2020-12-06 21:24 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                $this->searchTemplateInstaller(1);
Ответ выше

2020-12-06 21:24 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
Исправил

2020-12-06 21:28 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    /* Установка через поиск.
Данный метод используется для шаблонов типа 1 и 2 (мои покупки и готовые решения).
Он находит через поиск введенное решение и устанавливает его.

У 1 и 2 типа один и тот же способ установки (даже одни и те же xpath), я решил его сделать "универсальным" (избавиться от одинакового лишнего кода), передав через параметр $typeNumber, чтобы он понимал, какой все же тип будет устанавливаться и искал внутри его.

2020-12-06 21:54 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +     * Используется для 1 и 2 типа решения
1 и 2 тип решения $typeNumber. Посмотри про магические числа

2020-12-06 21:54 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        $I=$this->I;
исправлено

2020-12-06 21:56 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Вводит все поля и устанавливает всё до шаблона*/
исправил

2020-12-06 21:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    /*Формирует xpath адрес для полученного типа решения
переименовал в getTypeOfSiteSpanXpath. 
или использовать конкретно твой вариант?

просто мне показалось, что ты его как пример привел

2020-12-06 22:01 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    * @param $number
привел описание, так же изменил название переменной, чтобы её имя соответствовало имени в похожих методах

2020-12-06 22:05 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    {
исправлено

2020-12-06 22:05 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    public function __construct(\AcceptanceTester $I, $installIni)
исправлено

2020-12-06 22:05 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    protected $I;
исправлено

2020-12-06 22:05 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +class installPages
добавлено

2020-12-06 22:06 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +namespace Page\Acceptance;
исправлено

2020-12-07 07:55 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +    public static $searchResultOfSite = "//div[@class=\"site\"]";
изначально собирался писать по паттерну pageobject.
как я понял, данный паттерн подразумевает статичные методы.

я уже спрашивал про эту тему, ты сказал убрать, поэтому исправлено

2020-12-07 08:51 UTC, madGrant requested changes

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +    class getSolutionType {
У тебя класс содержит один публичный метод, который назван так же, как класс.
Подумай, чем реально является этот класс (клиентом api сервера обновлений).
Называть классы лучше называть существительным. getSolutionType - нормальное имя для метода, но не для класса.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +     * Данный класс содержит методы для получения типа загружаемого решения.
Здесь нужно описать, что делает класс, а не что он содержит.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private $installIni;
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        public function __construct(installIni $installIni) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +         * @param $type
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +         * @param array $params
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function buildUrl($type, $params = []) {
: string

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function getRemoteFile($url) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function checkXmlErrors($xml) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            unset($doc);
Нет смысла руками очищать память здесь.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function getDemositesList() {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function checkResponseErrors(DOMDocument $doc) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            if ($doc->documentElement->getAttribute('type') == 'exception') {
Не нужно делать лишний уровень вложенности.

Лучше писать код так:

```php
if ($doc->documentElement->getAttribute('type') !== 'exception') {
    return;
}

$xpath = new DOMXPath($doc);
$errors = $xpath->query('//error');
```

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        public function getSolutionType($name) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            }
Наверно, стоит как-то обработать ситуацию, когда тип не удалось получить

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +     * Данный класс отвечает за парсинг файла install.ini
А мне кажется, что данный класс представляет собой install.ini, а то, что он парсит, это уже особенности реализации, которые не нужно тут отражать.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        public $domain, $ip, $key;
phpDoc для каждого свойства, и лучше записывать по свойству на одну строку

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        public function __construct() {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $this->parseInstallIni();
Этот метод может кинуть исключение, кидать исключения в конструкторах - дурной тон.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +     * Данный класс отвечает за парсинг файла install.ini
А если ты таки хочешь сделать класс-парсер, то ему явно не нужны будут свойства с содержимым.

То есть, всевдокод такой будет:

```php
$config = $configParser->parse($configPath);
```

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            if (!file_exists(self::INSTALL_INI_PATH)) throw new \Exception("Не найден файл install.ini.
Лучше всегда использовать фигурные скобки в if, и выносить действие на следующую строку, так читабельнее.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +                throw new \Exception('Проблема с одним из полей файла install.ini. Убедитесь, что существуют все поля.');
А как потом это дебажить?) Будет лучше, если в ошибке будут содержаться отсутствующие ключи.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +     * Содержит основные методы для установки umi.cms2 и xpath.
Здесь нужно писать, что делает классс, а не что он содержит.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public $URL;
phpDoc, camelCase

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public $labelTypeOfSite;
phpDoc везде ниже

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public function __construct(\AcceptanceTester $acceptanceTester, $installIni) {
phpDoc

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        protected $installIni;
Поясни по  какому принципу у этих двух свойств режим доступа protected, а у тех, что выше - public.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        public $domain, $ip, $key;
Правило хорошего тона -  делать максимальный уровень доступа (private) ко всем свойствами и методам если они не используются снаружи.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Формирует xpath адрес для полученного типа решения
Формат phpDoc нарушен, надо так:

```php
/**
 * Формирует xpath адрес для полученного типа решения
 * @param int $type - тип решения, по умолчанию тип 1
 * @return string
 */

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Формирует xpath адрес для полученного типа решения
"тип 1" - что это? Магические цифры, это плохо.

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Данный метод отвечает за выбор в браузере типа шаблона.
Формат phpDoc нарушен, смотри пример выше

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        */
Лучше называть метода глаголами.
А в описании надо писать, что делает метод, где он используется - подскажет idea

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        */
Этот метод что-то заполняет, как я вижу

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Находит через поиск введенное решение и устанавливает его.
Формат phpDoc нарушен, смотри пример выше

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * Метод выбирает устанавливаемый шаблон.
Слово 'Метод ' можно опустить

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param $type - передается тип готового решения
тип аргумента не задан

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                {
Фигурную скобку в switch нужно писать на одном уровне с условием

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                case "free":
Нужно использовать фигурные скобки

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                case "paid":
Нужно использовать фигурные скобки

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                default:
Фигурную скобку в switch нужно писать на одном уровне с условием

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                        echo("\nНе найден шаблон с именем $templateName.\n"
В других местах ты кидал исключения, почему тут решил вывести сообщение в буфер?

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    break;
break нужен в default секции

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(4);
4 - магическое число

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
3 - магическое число

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(2);
2 - магическое число

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
3 - магическое число

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * Отвечает за заполнение формы администратора
Лучше писать "Заполняет форму" а не "Отвечает за заполнение формы"

2020-12-07 08:51 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public function svUserInstaller() {
Метод лучше называть глаголом.
Если метод заполняет форму, то почему бы его и не назвать как-нибудь типа "fillSvUserForm"

2020-12-07 08:51 UTC, madGrant commented on tests/acceptance/installCest.php
> +     * Основной класс программы (входная точка)
Что такое основной класс? Можно назвать его приложением, если это точка входа, а какие-либо роутинги и прочее не предусмотрены.

2020-12-07 08:51 UTC, madGrant commented on tests/acceptance/installCest.php
> +    class installCest {
`Cest` что это?

2020-12-07 08:51 UTC, madGrant commented on tests/acceptance/installCest.php
> +         * Основной метод.
Что за основной метод? тут надо написать, что метод делает.

2020-12-07 09:22 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +     * Данный класс отвечает за парсинг файла install.ini
исправлено

2020-12-07 09:24 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        public $domain, $ip, $key;
данные свойства используются в классе installPages, поэтому они паблик

про phpdoc исправил

2020-12-07 09:50 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        public function __construct() {
исправил

2020-12-07 09:55 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $this->parseInstallIni();
не знаю, как обработать эту ситуацию.
полностью отказаться от конструктора?

мне не нужно обрабатывать исключение, codeception их выводит и отображает причину проблемы

2020-12-07 09:56 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            if (!file_exists(self::INSTALL_INI_PATH)) throw new \Exception("Не найден файл install.ini.
исправлено

2020-12-07 09:56 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +                throw new \Exception('Проблема с одним из полей файла install.ini. Убедитесь, что существуют все поля.');
это у меня занесено в TODO, просто не успел по времени

2020-12-07 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +     * Содержит основные методы для установки umi.cms2 и xpath.
исправлено

2020-12-07 10:16 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public $URL;
исправлено

2020-12-07 10:35 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public $labelTypeOfSite;
исправлено

2020-12-07 10:36 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        protected $installIni;
у этих двух свойств исправил доступ на private, т.к. используются только внутри класса

2020-12-07 10:38 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public function __construct(\AcceptanceTester $acceptanceTester, $installIni) {
исправлено

2020-12-07 10:40 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Формирует xpath адрес для полученного типа решения
уже писал про это
https://github.com/Umisoft/gui-installation-script/pull/1#discussion_r537126259

не знаю как заменить эту "магическую" цифру

2020-12-07 10:41 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Данный метод отвечает за выбор в браузере типа шаблона.
исправлено

2020-12-07 10:45 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        */
исправлено

2020-12-07 10:45 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** Находит через поиск введенное решение и устанавливает его.
исправлено

2020-12-07 10:45 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +         * Метод выбирает устанавливаемый шаблон.
исправлено

2020-12-07 10:46 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                {
исправлено

2020-12-07 10:46 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                case "paid":
исправлено

2020-12-07 10:46 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                case "free":
исправлено

2020-12-07 10:46 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                default:
исправлено

2020-12-07 10:48 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                        echo("\nНе найден шаблон с именем $templateName.\n"
потому что исключения у меня нигде не обрабатываются, и если я выбрасываю исключение я хочу, чтобы установщик упал.

данная ситуация в моем понимании предполагает продолжение установки без шаблона, но необходимо проинформировать пользователя о ней

2020-12-07 10:49 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                    break;
ты имел в виду не нужен? посмотрел по регламенту, его там нет, поэтому убрал

2020-12-07 10:50 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(4);
https://github.com/Umisoft/gui-installation-script/pull/1#discussion_r537126259

2020-12-07 10:50 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
https://github.com/Umisoft/gui-installation-script/pull/1#discussion_r537126259

2020-12-07 10:50 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(2);
https://github.com/Umisoft/gui-installation-script/pull/1#discussion_r537126259

2020-12-07 10:50 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
https://github.com/Umisoft/gui-installation-script/pull/1#discussion_r537126259

2020-12-07 10:56 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +         * Отвечает за заполнение формы администратора
исправлено

2020-12-07 10:57 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public function svUserInstaller() {
исправлено

2020-12-07 11:02 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +     * Основной класс программы (входная точка)
не совсем понял, что ты имеешь в виду.
попробовал загуглить "приложение" в контексте языка php, но у меня выдается один мусор.

в других языках программирования со строгой типизацией (C#, Java) есть класс public static void main(), который является входной точкой во всю программу, и оттуда уже осуществляется всё управление.

в данном случае, этот класс аналогично передается в Codeception, из которого уже возможны все остальные действия.

2020-12-07 11:07 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    class installCest {
обязательное требование фреймворка Codeception в наименовании класса, которому нужно окончание Cest и без которого ничего работать не будет
https://codeception.com/docs/02-GettingStarted#Writing-a-Sample-Test
https://codeception.com/docs/07-AdvancedUsage

2020-12-07 11:29 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +         * Основной метод.
Расширил phpdoc

2020-12-08 07:44 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +    class getSolutionType {
исправлено

2020-12-08 07:46 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private $installIni;
исправлено

2020-12-08 07:47 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +     * Данный класс содержит методы для получения типа загружаемого решения.
исправлено

2020-12-08 07:51 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        public function __construct(installIni $installIni) {
исправлено

2020-12-08 07:54 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +         * @param $type
исправлено

2020-12-08 07:54 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +         * @param array $params
исправлено

2020-12-08 07:55 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function buildUrl($type, $params = []) {
исправлено

2020-12-08 07:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function getRemoteFile($url) {
исправлено

2020-12-08 07:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            unset($doc);
исправлено

2020-12-08 08:03 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function checkXmlErrors($xml) {
исправлено

2020-12-08 08:05 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function getDemositesList() {
исправлено

2020-12-08 08:06 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        private function checkResponseErrors(DOMDocument $doc) {
исправлено

2020-12-08 08:07 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            if ($doc->documentElement->getAttribute('type') == 'exception') {
исправлено

2020-12-08 08:10 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +        public function getSolutionType($name) {
исправлено

2020-12-08 08:10 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/getSolutionType.php
> +            }
она обрабатывается дальше, в классе installPages в конструкции switch

2020-12-08 08:11 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +         * Отвечает за заполнение формы администратора
исправлено

2020-12-08 08:48 UTC, madGrant requested changes

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +     * @return $name - имя типа устанавливаемого шаблона.
Класс у нас что-то умеет возвращать?)
@return надо писать только у методов

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +        /** @var $installIni - переменная класса installIni, нужна для создания параметров GET запроса */
тип не описан, надо так:

/** @var string $foo bar */

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +         * @param $type - тип запроса
не описан тип аргумента

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +         * @param $url - URL адрес
не описан тип аргумента

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +        private function checkResponseErrors(DOMDocument $doc) {
Не описан аргумент $doc

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +        public function getSolutionType($name) : string {
Публичный метод стоит писать перед приватными в рамках класса

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +            }
Не вижу обработки ситуации, когда тип не найден. Тогда у тебя метод вернет null и не пройдет типизацию возвращаемого значения (: string)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +    {
Фигурная скобка должна быть на предыдущей строке

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +    */
отступ поехал

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $domain - содержит domain из секции [LICENSE] файла install.ini */
не описан тип свойства

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $domain - содержит domain из секции [LICENSE] файла install.ini */
не надо описывать, откуда это значение.
Достаточно просто написать, что это домен устанавливаемого сайта

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $ip - содержит ip из секции [LICENSE] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $key -  содержит key из секции [LICENSE] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $domain - содержит domain из секции [LICENSE] файла install.ini */
не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $host -  содержит host из секции [DB] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbuser -  содержит user из секции [DB] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис
- camelCase

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbpassword -  содержит password из секции [DB] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис
- camelCase

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbname -  содержит dbname из секции [DB] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис
- camelCase

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $templateName -  содержит name из секции [DEMOSITE] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $login -  содержит login из секции [SUPERVISOR] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $password -  содержит password из секции [SUPERVISOR] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $email -  содержит email из секции [SUPERVISOR] файла install.ini */
- не описан тип свойства
- не надо описывать, откуда это значение.
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        /** Путь к install.ini. Временное решение (хардкод). Позже будет изменен */
Формат описания константы:

```php
/** @const array ATTRIBUTE_LIST список атрибутов изображения  */
const ATTRIBUTE_LIST = ['alt', 'title', 'ord'];
```

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $this->parseInstallIni();
Возможно не стоит сразу парсить файл?
Твой класс  - контейнер для данных install.ini.
Можно добавить ему отдельный метод parseFromFile(string  $filePath), который вызывать руками

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +         * Данный метод парсит install.ini в переменные класса installIni
`Данный метод` - лишнее

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        {
уровень фигурной скобки

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +        {
уровень фигурной скобки

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $iniArray = parse_ini_file(self::INSTALL_INI_PATH, true);
Не надо использовать в нейминге переменных обозначения типов данных (в данном случае array)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $licenseTestArray = ['domain', 'ip', 'key'];
Не надо использовать в нейминге переменных обозначения типов данных (в данном случае array)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $licenseArray = $iniArray['LICENSE'];
Не надо использовать в нейминге переменных обозначения типов данных (в данном случае array)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $dbArray = $iniArray['DB'];
Не надо использовать в нейминге переменных обозначения типов данных (в данном случае array)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $svArray = $iniArray['SUPERVISOR'];
Не надо использовать в нейминге переменных обозначения типов данных (в данном случае array)

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $url - содержит url адрес страницы с /install.php */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public $labelTypeOfSite;
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $keyField - содержит xpath к полю ввода "Введите ключ"*/
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $nextButton - содержит xpath к кнопке "Далее   >", которая используется до установки шаблона */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $templateNextButton - содержит xpath к кнопке "Далее   »", которая используется при установке шаблона */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbHostField - содержит xpath к полю ввода "Имя хоста" */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbNameField - содержит xpath к полю ввода "Имя базы данных" */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbUserField - содержит xpath к полю ввода "Логин" при настройке БД */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbPasswordField - содержит xpath к полю ввода "Пароль" при настройке БД */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $backupCheckbox - содержит xpath к чекбоксу "Подтверждаю, что сделал бэкап всех файлов,
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $showLogs - содержит xpath к гиперссылке "Показать ход установки" */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $loginField - содержит xpath к полю ввода "Логин" при настройке суперпользователя */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $emailField - содержит xpath к полю ввода "E-mail" при настройке суперпользователя */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $passwordField - содержит xpath к полю ввода "Пароль" при настройке суперпользователя */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $verifyPasswordField - содержит xpath к полю ввода "Пароль ещё раз" при настройке суперпользователя */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $systemInstalledText - содержит xpath к тексту "Установка системы завершена" */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $typeOfSiteSearchField - содержит xpath к полю ввода поиска "Введите номер сайта" */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $typeOfSiteSearchButton - содержит xpath к кнопке "Найти" на странице поиска */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $searchResultOfSite - содержит xpath к результату поиска */
не описан тип свойства
не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $acceptanceTester - содержит экземпляр класса для управления фреймворком */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $installIni - содержит экземпляр installIni */
- не описан тип свойства
- не нужен дефис

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param $type - передается тип готового решения
Не описан тип аргумента

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param int $type - тип решения, по умолчанию тип 1
Что такое "тип 1"?

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * На данный момент используется только для 1 и 2 типов решения
Что такое 1 и 2 типы решения?

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                        echo("\nНе найден шаблон с именем $templateName.\n"
Лучше кинуть исключение

2020-12-08 08:48 UTC, madGrant commented on tests/acceptance/installCest.php
> +    class installCest {
Из этого списка лучше использовать 'Test', так будет понятнее

2020-12-08 08:48 UTC, madGrant commented on tests/acceptance/installCest.php
> +     * Основной класс программы (входная точка)
Не важно, что куда передается. Класс должен своим именем и phpDoc'ом передавать своё назначение.
Как я понимаю, это класс тестов инсталлятора? Может его так назвать и описать?

2020-12-08 08:48 UTC, madGrant commented on tests/acceptance/installCest.php
> +         * Основной метод.
Ты не ответил на вопрос про основной метод)
Вероятно, этот метод запускает выполнение тестов, может его так и назвать?
Нет необходимости перечислять в phpDoc все особенности его реализации, по каким url'ам он ходит и тд.

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(2);
Заведи в классе константы с нормальными названиями и описаниями, равны они будут твоим числам, но в коде фигурировать не будут.

То есть:

```php
const FREE_SOLUTION_TYPE =1;

public function getType($type = self::FREE_SOLUTION_TYPE) {

}
```

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
Заведи в классе константы с нормальными названиями и описаниями, равны они будут твоим числам, но в коде фигурировать не будут.

То есть:

```php
const FREE_SOLUTION_TYPE =1;

public function getType($type = self::FREE_SOLUTION_TYPE) {

}
```

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(3);
Заведи в классе константы с нормальными названиями и описаниями, равны они будут твоим числам, но в коде фигурировать не будут.

То есть:

```php
const FREE_SOLUTION_TYPE =1;

public function getType($type = self::FREE_SOLUTION_TYPE) {

}
```

2020-12-08 08:48 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +                    $this->selectTypeOfSite(4);
Заведи в классе константы с нормальными названиями и описаниями, равны они будут твоим числам, но в коде фигурировать не будут.

То есть:

```php
const FREE_SOLUTION_TYPE =1;

public function getType($type = self::FREE_SOLUTION_TYPE) {

}
```

2020-12-08 08:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +     * @return $name - имя типа устанавливаемого шаблона.
исправлено

2020-12-08 08:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +        /** @var $installIni - переменная класса installIni, нужна для создания параметров GET запроса */
исправлено

2020-12-08 09:00 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +         * @param $type - тип запроса
исправлено

2020-12-08 09:01 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +         * @param $url - URL адрес
исправено

2020-12-08 09:02 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +        private function checkResponseErrors(DOMDocument $doc) {
исправлено

2020-12-08 09:03 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +        public function getSolutionType($name) : string {
исправлено

2020-12-08 09:07 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +            }
убрал типизацию, обработчик null имеется в классе installPages

2020-12-08 09:07 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +    {
исправлено

2020-12-08 09:07 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +    */
исправлено

2020-12-08 09:12 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $domain - содержит domain из секции [LICENSE] файла install.ini */
исправлено

2020-12-08 09:12 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $ip - содержит ip из секции [LICENSE] файла install.ini */
исправлено

2020-12-08 09:13 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $key -  содержит key из секции [LICENSE] файла install.ini */
исправлено

2020-12-08 09:13 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $host -  содержит host из секции [DB] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbuser -  содержит user из секции [DB] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbpassword -  содержит password из секции [DB] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $dbname -  содержит dbname из секции [DB] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $login -  содержит login из секции [SUPERVISOR] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $password -  содержит password из секции [SUPERVISOR] файла install.ini */
исправлено

2020-12-08 09:15 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** @var $email -  содержит email из секции [SUPERVISOR] файла install.ini */
исправлено

2020-12-08 09:16 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        /** Путь к install.ini. Временное решение (хардкод). Позже будет изменен */
исправлено

2020-12-08 09:26 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +         * Данный метод парсит install.ini в переменные класса installIni
Убрал

2020-12-08 09:27 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        {
исправлено

2020-12-08 09:27 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +        {
исправлено

2020-12-08 09:30 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $iniArray = parse_ini_file(self::INSTALL_INI_PATH, true);
исправлено

2020-12-08 09:30 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $licenseTestArray = ['domain', 'ip', 'key'];
исправлено

2020-12-08 09:32 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $licenseArray = $iniArray['LICENSE'];
исправлено

2020-12-08 09:32 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $dbArray = $iniArray['DB'];
исправлено

2020-12-08 09:32 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installIni.php
> +            $svArray = $iniArray['SUPERVISOR'];
исправлено

2020-12-08 09:57 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $url - содержит url адрес страницы с /install.php */
исправлено

2020-12-08 09:57 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public $labelTypeOfSite;
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $keyField - содержит xpath к полю ввода "Введите ключ"*/
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $nextButton - содержит xpath к кнопке "Далее   >", которая используется до установки шаблона */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $templateNextButton - содержит xpath к кнопке "Далее   »", которая используется при установке шаблона */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbHostField - содержит xpath к полю ввода "Имя хоста" */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbNameField - содержит xpath к полю ввода "Имя базы данных" */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbUserField - содержит xpath к полю ввода "Логин" при настройке БД */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $dbPasswordField - содержит xpath к полю ввода "Пароль" при настройке БД */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $backupCheckbox - содержит xpath к чекбоксу "Подтверждаю, что сделал бэкап всех файлов,
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $showLogs - содержит xpath к гиперссылке "Показать ход установки" */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $loginField - содержит xpath к полю ввода "Логин" при настройке суперпользователя */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $emailField - содержит xpath к полю ввода "E-mail" при настройке суперпользователя */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $passwordField - содержит xpath к полю ввода "Пароль" при настройке суперпользователя */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $verifyPasswordField - содержит xpath к полю ввода "Пароль ещё раз" при настройке суперпользователя */
исправлено

2020-12-08 09:58 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $systemInstalledText - содержит xpath к тексту "Установка системы завершена" */
исправлено

2020-12-08 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $typeOfSiteSearchField - содержит xpath к полю ввода поиска "Введите номер сайта" */
исправлено

2020-12-08 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $typeOfSiteSearchButton - содержит xpath к кнопке "Найти" на странице поиска */
исправлено

2020-12-08 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $searchResultOfSite - содержит xpath к результату поиска */
исправлено

2020-12-08 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $acceptanceTester - содержит экземпляр класса для управления фреймворком */
исправлено

2020-12-08 09:59 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        /** @var $installIni - содержит экземпляр installIni */
исправлено

2020-12-08 10:00 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param $type - передается тип готового решения
исправлено

2020-12-08 10:08 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    class installCest {
Суффикс "Test" предполагает, что я буду писать юнит тесты
https://codeception.com/docs/05-UnitTests
у которых совсем другая логика и синтаксис

Суффикс Cept предполагает, что я буду писать сценарий в 1 класс
Суффикс Cest предполагает, что я буду работать с классами
https://stackoverflow.com/questions/27296495/codeception-what-is-the-difference-between-cest-and-cept

если его нужно поменять, то нужно переделывать весь код, т.к. если просто сделать refactor rename выводится ошибка, что тесты отсутствуют.

2020-12-08 12:17 UTC, madGrant requested changes

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +            if ($types->length==0) {
пробелы до и после ==

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +                throw new \Exception("\nНе найден шаблон с именем $name.\n"
Если тебе нужны переводы строк, то нужно использовать константу PHP_EOL.
А нужны ли они реально? Обычно так не делают в сообщениях исключений.

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +                foreach ($errors as $error) {
Отступ

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installIni.php
> +            $this->parseInstallIni();
Этот комментарий не решен

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +        public $searchResultOfSite = "//div[@class=\"site\"]";
Повторю вопрос - почему свойства публичные, если они не используются вне класса?
По умолчанию всё следует делать private

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param int $type - тип решения, по умолчанию тип 1
добавь сюда отсылку на константу, чтобы вопрос был исчерпан

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param $type - передается тип готового решения
все еще не описан

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * @param $type - передается тип готового решения
и дефис не нужен

2020-12-08 12:17 UTC, madGrant commented on tests/_support/Page/Acceptance/installPages.php
> +         * На данный момент используется только для 1 и 2 типов решения
Сделай отсылку на константы, например так:

@see self::ИМЯ_КОНСТАНТЫ

2020-12-08 12:17 UTC, madGrant commented on tests/acceptance/installCest.php
> +    */
Отступов

2020-12-08 12:17 UTC, madGrant commented on tests/acceptance/installCest.php
> +         * Тест установки umi.cms
Тестирует установку umi.cms

2020-12-08 12:19 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +            if ($types->length==0) {
исправлено

2020-12-08 12:19 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +                throw new \Exception("\nНе найден шаблон с именем $name.\n"
ок, убрал перенос

2020-12-08 12:20 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +                foreach ($errors as $error) {
исправил

2020-12-08 12:24 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/installPages.php
> +        public $searchResultOfSite = "//div[@class=\"site\"]";
исправлено

2020-12-08 12:25 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +         * Тест установки umi.cms
исправлено

2020-12-08 12:28 UTC, SeeleBlack commented on tests/acceptance/installCest.php
> +    */
исправлено

2020-12-08 12:44 UTC, madGrant requested changes

2020-12-08 12:44 UTC, madGrant commented on tests/_support/Page/Acceptance/apiClient.php
> +        public function getSolutionType($name) {
Не описан аргумент $name

2020-12-08 12:48 UTC, SeeleBlack commented on tests/_support/Page/Acceptance/apiClient.php
> +        public function getSolutionType($name) {
исправлено

2020-12-08 12:48 UTC, madGrant approved these changes

2020-12-08 12:48 UTC, merged